# Generated by Django 5.2.12 on 2026-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
