# Generated by Django 5.2.12 on 2026-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='type_document',
            field=models.CharField(choices=[('facture', 'Facture'), ('proforma', 'Facture Proforma'), ('livraison', 'Bordereau de Livraison')], default='facture', max_length=20),
        ),
    ]
