# Generated by Django 5.2.12 on 2026-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='observation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
