# Generated by Django 4.2.17 on 2024-12-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_adresse_client_prenom_and_more'),
        ('transactions', '0003_client_produitservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_produit', to='transactions.produitservice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_service', to='transactions.produitservice'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
