# Generated by Django 4.2.17 on 2024-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_facture_client_alter_transaction_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
