# Generated by Django 4.2.17 on 2024-12-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_montant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignefacture',
            old_name='prix_total',
            new_name='montant',
        ),
    ]
