# Generated by Django 4.2.17 on 2024-12-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_lignefacture_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
