# Generated by Django 4.2.17 on 2024-12-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits_services', '0002_facture'),
        ('transactions', '0008_alter_lignefacture_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_produit', to='produits_services.produit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_service', to='produits_services.service'),
        ),
    ]
