# Generated by Django 4.2.17 on 2024-12-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_produit_alter_transaction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.facture'),
        ),
    ]
