# Generated by Django 4.2.17 on 2024-12-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_ouverte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ouverte',
        ),
    ]
