# Generated by Django 4.2.17 on 2024-12-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits_services', '0002_facture'),
        ('transactions', '0013_facture_ouverte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignefacture',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_emission',
            field=models.DateField(default='2024-12-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='lignes',
            field=models.ManyToManyField(blank=True, to='transactions.lignefacture'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='produit_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits_services.produit'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
