# Generated by Django 4.2.17 on 2024-12-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits_services', '0003_produitouservice'),
        ('transactions', '0015_alter_facture_date_emission_alter_facture_ouverte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitservice',
            old_name='prix_unitaire',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='quantite',
        ),
        migrations.AddField(
            model_name='facture',
            name='lignes',
            field=models.ManyToManyField(related_name='factures', to='transactions.lignefacture'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='produit_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits_services.produitouservice'),
        ),
        migrations.AlterField(
            model_name='produitservice',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
