# Generated by Django 4.2.17 on 2024-12-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_rename_prix_unitaire_produitservice_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
