# Generated by Django 4.2.17 on 2024-12-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_lignefacture_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='_updating_total',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
