# Generated by Django 4.2.17 on 2024-12-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_delete_produitservice_lignefacture_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='lignes',
        ),
    ]
