# Generated by Django 4.2.17 on 2024-12-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_services', '0002_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitOuService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('produit', 'Produit'), ('service', 'Service')], max_length=10)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
