# Generated by Django 4.2.17 on 2024-12-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_rename_prix_unitaire_produitservice_prix_and_more'),
        ('produits_services', '0003_produitouservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
