# Generated by Django 4.2.17 on 2024-12-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits_services', '0004_delete_produit_delete_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitouservice',
            old_name='prix',
            new_name='prix_unitaire',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
